### PR TITLE
Updated coin sprites

### PR DESCRIPTION
**Pull request by tobbi**
Thanks to @moochinook for the co(i)ntribution

Reference thread:
http://forum.freegamedev.net/viewtopic.php?f=68&t=7053#p70004

### CODE REVIEW

**Comment by maxteufel** [comment]
The color of the coin counter at the top right should be changed too.

Also, why change this? The old ones didn't look bad. Not that I don't like the new ones. I like both versions.

**Comment by Hypernoot** [comment]
I think, these are better, because shiny stuff looks modern in my opinion. The coin counter doesn't have to be changed, because it's not so big change.

**Comment by maxteufel** [comment]
> [...], because it's not so big change.

If this is a long term change, it should be updated too. For consistency. And it probably shouldn't take much time for moochinook. The changes were probably done using the color correction tool or so.

**Comment by Hypernoot** [comment]
https://github.com/SuperTux/data/blob/master/images/engine/hud/coins-0.png
I'm not sure whether anyone would notice this tiny change, but wouldn't be so hard.

**Comment by maxteufel** [comment]
I noticed it actually while playing. Otherwise I wouldn't have thought about it.

**Comment by Hypernoot** [comment]
You're right, these coins are a bit more orange. Did you know that the coin was changed the most times? So except this it's OK. Yes and change fish to € :smile: !

**Comment by tobbi** [comment]
I think the new color resembles those of coins more.

**Comment by Hypernoot** [comment]
r+

**Comment by maxteufel** [comment]
Looks good to merge.

**Comment by uafr** [comment]
On 2016-07-18 Hume2 notifications@github.com wrote:

> You're right, these coins are a bit more orange. Did you know that
> the coin was changed the most times? So except this it's OK. Yes
> and change fish to € :smile: !

Please don't add any real currency symbol. Otherwise prepare for lots of
change requests to Ruble, Dogecoin, Yuan, or whatever. If you really 
need another symbol instead of 🐟 there is the currency sign ¤.

**Comment by maxteufel** [comment]
> Please don't add any real currency symbol.

I don't think it was a serious suggestion.

**Comment by Hypernoot** [comment]
This wasn't a serious suggestion, just a joke. Quite a lot of games use $, so why not €?

**Pull request merged**
