### PR TITLE
Update levels/world1/bonus.stl

### PR DESCRIPTION
**Pull request by Rusty-Box**
- Replace the old water with the new water.
- Change wooden platforms to small ice floes.

### CODE REVIEW

**Comment by Hypernoot** [comment]
r+

**Comment by maxteufel** [comment]
You missed a wooden platform: kegcdkar

**Comment by Hypernoot** [comment]
This is not a platform, is it? This kind of wood is commonly used in the icy island.

**Comment by maxteufel** [comment]
Why are the others platforms then, and this not?

**Comment by maxteufel** [comment]
Can you fix that missing tile, @Rusty-Box 
hbc842ji

**Comment by maxteufel** [comment]
Thanks for the pull request, @Rusty-Box. :+1:

**Pull request closed without merging**
