### PR TITLE
Make the cameras in The Silent Walls less annoying

### PR DESCRIPTION
**Pull request by brmbrmcar**
You don't have to merge this, but I think the SuperTux community want this.

### CODE REVIEW

**Comment by tobbi** [comment]
Can you explain the change to me?

**Comment by brmbrmcar** [comment]
When you go past the camera with the wood moving around, it now waits a second to close the other gate.

**Comment by brmbrmcar** [comment]
I have no idea what happened at line 16.

**Comment by maxteufel** [comment]
```
18:16:06 <@maxteufel> https://github.com/SuperTux/data/pull/4 isn't this intended to be hard?
18:16:26 <@tobbi> Oh, yes...
18:16:34 <@tobbi> Yes, it is one of the castle levels.
18:16:46 <@tobbi> I don't think we want this.
18:16:48 <@maxteufel> close?
18:16:53 <@tobbi> Yeah, let's close this.
```

**Pull request closed without merging**
